server.port=8080

spring.datasource.url=jdbc:oracle:thin:@mahmf_high
spring.datasource.username=ADMIN
spring.datasource.password=MAHMFintegradora5
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=/home/ubuntu/Wallet_MAHMF
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=/home/ubuntu/Wallet_MAHMF

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.secret=clave-super-secreta-de-al-menos-32-caracteres-utez-2026
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahmf.verificacion@gmail.com
spring.mail.password=mcgkqyedlrztrmnu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=/home/ubuntu/uploads
app.upload.base-url=http://129.146.137.202:8080/files

logging.level.root=WARN
logging.level.com.utez.misestadias=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

spring.application.name=misestadias