# --- SERVIDOR ---
server.port=8080

# --- DATASOURCE (Oracle) ---
# Formato SID:     jdbc:oracle:thin:@HOST:PORT:SID
# Formato Service: jdbc:oracle:thin:@//HOST:PORT/SERVICE_NAME
spring.datasource.url=jdbc:oracle:thin:@//HOST:PORT/SERVICE_NAME
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASEÑA
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.application.name=misestadias


# --- JWT CONFIGURATION ---
jwt.secret=clave-super-secreta-de-al-menos-32-caracteres-utez-2026
jwt.expiration=86400000

