server.port=8080

# --- DATASOURCE (Oracle Autonomous Cloud + Wallet) ---
spring.datasource.url=jdbc:oracle:thin:@mahmf_high
spring.datasource.username=ADMIN
spring.datasource.password=MAHMFintegradora5
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- WALLET: RUTAS ACTUALIZADAS PARA TU PC ---
# --- WALLET: RUTA CORREGIDA HACIA LA SUB-CARPETA ---
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=C:\\WALLET INTV\\Wallet_MAHMF
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=C:\\WALLET INTV\\Wallet_MAHMF

# Nota: Si el espacio en "WALLET INTV" te sigue dando problemas,
# renombra la carpeta a WALLET_INTV (sin espacios) y quita el espacio aquí también.

spring.jpa.hibernate.ddl-auto=update

# Dialecto para Oracle 12c+
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Debug SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- NOMBRE DE LA APP ---
spring.application.name=misestadias

# --- JWT (24 Horas) ---
jwt.secret=clave-super-secreta-de-al-menos-32-caracteres-utez-2026
jwt.expiration=86400000

spring.jpa.open-in-view=false

# --- EMAIL (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahmf.verificacion@gmail.com
spring.mail.password=mcgkqyedlrztrmnu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

logging.level.org.springframework.security.config=ERROR